title: <p align="center"> Charu Tewari </p>
logo: /assets/img/profile_picture.PNG

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/charu-tewari-2282511b3/">LinkedIn</a> |
  <a href="https://github.com/Charu244">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
